In [1]:
import pandas as pd
df= pd.read_excel('file/score.xlsx',index_col="지원번호")

In [5]:
#index를 가지고 정렬
df.sort_index(ascending=False)

#각컬럼을 가지고 정렬
#df.sort_values('키',ascending=False)

# df.sort_values(['국어','영어'],ascending=False)
df.sort_values(['국어','영어'],ascending=[False,True])

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
8번    승근열  디지털고  190  100   85   90  95  95          C#
1번    강나래   구로고  197   90   85  100  95  85      Python
3번    강호림   구로고  168   80   75   70  80  75  Javascript
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
2번    강태원   구로고  184   40   35   50  55  25        Java
4번    김수찬   구로고  187   40   60   70  75  80         NaN
5번    김재욱   구로고  188   15   20   10  35  10         NaN

In [24]:
df =pd.read_csv('file/jumin08_2.csv',index_col="행정구역")
df2 = df[['2026년08월_총인구수','2026년08월_세대수']]
df2['2026년08월_총인구수'] = df2['2026년08월_총인구수'].str.replace(',','').astype(int)
df2['2026년08월_세대수'] = df2['2026년08월_세대수'].str.replace(',','').astype(int)

In [25]:
df2.info()
df2.sort_values('2026년08월_총인구수')

<class 'pandas.DataFrame'>
Index: 17 entries, 전국  (1000000000) to 제주특별자치도  (5000000000)
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   2026년08월_총인구수  17 non-null     int64
 1   2026년08월_세대수   17 non-null     int64
dtypes: int64(2)
memory usage: 408.0+ bytes

                         2026년08월_총인구수  2026년08월_세대수
행정구역
세종특별자치시  (3600000000)           390738        165930
제주특별자치도  (5000000000)           662681        317767
울산광역시  (3100000000)            1086373        502387
대전광역시  (3000000000)            1442838        706437
강원특별자치도  (5100000000)          1506662        775882
충청북도  (4300000000)             1601367        808665
전북특별자치도  (5200000000)          1716965        874337
충청남도  (4400000000)             2138938       1072860
대구광역시  (2700000000)            2346277       1123265
경상북도  (4700000000)             2492677       1303782
인천광역시  (2800000000)            3066185       1418345
전남광주통합특별시  (1200000000)        3155803       1579291
경상남도  (4800000000)             3191645       1558906
부산광역시  (2600000000)            3229467       1583256
서울특별시  (1100000000)            9281625       4525061
경기도  (4100000000)             13773918       6189087
전국  (1000000000)              51084159      24505258

In [30]:
df =pd.read_csv('file/jumin08_2.csv',index_col="행정구역")

In [20]:
#행정구역 역순정렬
df.sort_index()

,2026년08월_총인구수,2026년08월_세대수,2026년08월_세대당 인구,2026년08월_남자 인구수,2026년08월_여자 인구수,2026년08월_남여 비율
행정구역,,,,,,
강원특별자치도 (5100000000),"1,506,662","775,882",1.94,"757,981","748,681",1.01
경기도 (4100000000),"13,773,918","6,189,087",2.23,"6,914,277","6,859,641",1.01
경상남도 (4800000000),"3,191,645","1,558,906",2.05,"1,609,943","1,581,702",1.02
경상북도 (4700000000),"2,492,677","1,303,782",1.91,"1,262,786","1,229,891",1.03
대구광역시 (2700000000),"2,346,277","1,123,265",2.09,"1,148,130","1,198,147",0.96
대전광역시 (3000000000),"1,442,838","706,437",2.04,"718,413","724,425",0.99
부산광역시 (2600000000),"3,229,467","1,583,256",2.04,"1,568,318","1,661,149",0.94
서울특별시 (1100000000),"9,281,625","4,525,061",2.05,"4,466,290","4,815,335",0.93
세종특별자치시 (3600000000),"390,738","165,930",2.35,"194,589","196,149",0.99
울산광역시 (3100000000),"1,086,373","502,387",2.16,"560,121","526,252",1.06
인천광역시 (2800000000),"3,066,185","1,418,345",2.16,"1,530,650","1,535,535",1.00
전국 (1000000000),"51,084,159","24,505,258",2.08,"25,412,088","25,672,071",0.99
전남광주통합특별시 (1200000000),"3,155,803","1,579,291",2.00,"1,578,180","1,577,623",1.00
전북특별자치도 (5200000000),"1,716,965","874,337",1.96,"855,796","861,169",0.99
제주특별자치도 (5000000000),"662,681","317,767",2.09,"331,063","331,618",1.00
충청남도 (4400000000),"2,138,938","1,072,860",1.99,"1,098,834","1,040,104",1.06
충청북도 (4300000000),"1,601,367","808,665",1.98,"816,717","784,650",1.04

In [32]:
# 행정구역으로 역순정렬
# df.sort_values('2026년08월_총인구수')
df['2026년08월_총인구수'] = df['2026년08월_총인구수'].str.replace(',','').astype(int)

In [33]:
df= pd.read_excel('file/students.xlsx',index_col='번호')
df

            이름    학교  학년    키  국어  영어  수학    SW특기
번호
1      Eadmund   신림고   2  171  56  92  60       c
2       Kirbee   구로고   1  199  53  10  45       C
3    Appolonia   구로고   3  193  77  52  81       C
4        Avery   구로고   2  187  59  35  43       C
5       Dallis  디지털고   1  209  97  57  76       C
..         ...   ...  ..  ...  ..  ..  ..     ...
96        Luke   신림고   3  187  91  63  59  Python
97        Nada   구로고   3  170  60  89  55  PYTHON
98       Fiona   신림고   1  200  97  95  84       C
99        Leif   구로고   2  192  96  84  34  PYTHON
100   Jonathan  디지털고   2  195  84  63  80    JAVA

[100 rows x 8 columns]

In [40]:
# 학교순차정렬, 이름 역순정렬
df.sort_values(['학교','이름'],ascending=True)
df.sort_values(['학교','이름'],ascending=[True,False]).tail(20)

            이름   학교  학년    키  국어  영어  수학        SW특기
번호
66      Joanie  신림고   1  200  75  24  85        java
10       Honor  신림고   2  186  83  11  58      PYTHON
32      Hamnet  신림고   3  171  95  55  65  Javascript
57       Grier  신림고   2  162  64  75  68           C
7         Gaye  신림고   3  192  65  27  86      PYTHON
61        Gage  신림고   3  189  58  13  83
98       Fiona  신림고   1  200  97  95  84           C
21   Evangelia  신림고   2  190  51  71  83      PYTHON
88       Emile  신림고   2  199  83  26  68      PYTHON
20      Emelia  신림고   1  199  85  27  31  Javascript
1      Eadmund  신림고   2  171  56  92  60           c
85     Diahann  신림고   3  189  90  26  83      PYTHON
80      Dallas  신림고   2  173  65  33  45      Python
43        Dale  신림고   2  192  91  96  55      PYTHON
95  Clementine  신림고   1  194  71  13  81        JAVA
52        Buck  신림고   2  187  93  71  75           c
71       Booth  신림고   3  208  86  53  44      python
72       Beryl  신림고   3  171  82  26  55           C
53  Anthiathia  신림고   3  178  76   7  52      python
28       Alard  신림고   1  178  96   1  48